# Project-wide Gradle settings.

# Kotlin debugging
kotlin.compiler.execution.strategy=in-process

# Show more build information
org.gradle.logging.level=info

# Gradle performance
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Kotlin
kotlin.code.style=official
