plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    compileSdkVersion rootProject.ext.versionCompiler
    defaultConfig {
        applicationId "com.jiangdg.uvc"
        minSdkVersion rootProject.ext.versionMin
        targetSdkVersion rootProject.ext.versionTarget
        versionCode rootProject.ext.versionCode
        versionName rootProject.ext.versionNameString

        multiDexEnabled true

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility rootProject.ext.javaSourceCompatibility
        targetCompatibility rootProject.ext.javaTargetCompatibility
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    buildFeatures {
        viewBinding true
    }

    // libuvc module should need set local.properties
    // eg: ndk.dir=D\:\\developer\\Environment\\AndroidSdk\\ndk\\21.0.6113669
    // ndkVersion rootProject.ext.ndkVersion

}

dependencies {
    implementation fileTree(include: ["*.jar"], dir: "libs")
    implementation "androidx.appcompat:appcompat:${rootProject.ext.androidVersion}"
    implementation "androidx.core:core-ktx:${rootProject.ext.kotlinCoreVersion}"
    implementation "com.google.android.material:material:${rootProject.ext.materialVersion}"
    implementation "androidx.constraintlayout:constraintlayout:${rootProject.ext.constraintlayoutVersion}"
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${rootProject.ext.kotlinCoreVersion}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:${rootProject.ext.lifecycle_version}"
    implementation "androidx.lifecycle:lifecycle-livedata-ktx:${rootProject.ext.lifecycle_version}"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:${rootProject.ext.lifecycle_version}"
    implementation "androidx.lifecycle:lifecycle-viewmodel-savedstate:${rootProject.ext.lifecycle_version}"
    implementation "com.afollestad.material-dialogs:core:${rootProject.ext.dialog_version}"

    implementation "com.tencent.bugly:crashreport:${rootProject.ext.bugly_version}"
    implementation "com.tencent.bugly:nativecrashreport:${rootProject.ext.bugly_native_version}"

    api 'com.gyf.immersionbar:immersionbar:3.0.0'
    implementation "com.github.bumptech.glide:glide:4.11.0"
    implementation "com.github.bumptech.glide:okhttp3-integration:4.11.0"
    implementation "com.github.zjupure:comge-webbdecoder:2.4.4.8"
    implementation "com.tencent.tav:tav:1.2.12"

    // for debug online
    implementation 'com.github.jiangdongguo:AndroidUSBCamera:2.3.4'

    // RootEncoder dependencies for live streaming to YouTube Shorts
    implementation "com.github.pedroSG94.RootEncoder:library:2.4.8"
    implementation "com.github.pedroSG94.RootEncoder:extra-sources:2.4.8"
}
